# Generated by Django 5.0.7 on 2025-12-22 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUploadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255, verbose_name='Nombre del archivo')),
                ('file_type', models.CharField(choices=[('XLS', 'Excel XLS'), ('XLSX', 'Excel XLSX'), ('CSV', 'CSV')], max_length=10, verbose_name='Tipo de archivo')),
                ('plan_type', models.CharField(choices=[('PLAN_NORMAL', 'Plan Normal'), ('PLAN_R', 'Plan R')], help_text='Tipo de plan importado', max_length=20)),
                ('total_rows', models.IntegerField(default=0, verbose_name='Total de filas en archivo')),
                ('records_processed', models.IntegerField(default=0, verbose_name='Registros procesados')),
                ('records_success', models.IntegerField(default=0, verbose_name='Registros exitosos')),
                ('records_failed', models.IntegerField(default=0, verbose_name='Registros fallidos')),
                ('error_log', models.JSONField(blank=True, null=True, verbose_name='Log de errores')),
                ('processing_time', models.FloatField(blank=True, null=True, verbose_name='Tiempo de procesamiento (segundos)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de carga')),
                ('status', models.CharField(choices=[('SUCCESS', 'Exitoso'), ('PARTIAL', 'Parcial'), ('FAILED', 'Fallido')], default='SUCCESS', max_length=20)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='file_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Carga de Archivo',
                'verbose_name_plural': 'Logs de Cargas de Archivos',
                'db_table': 'operations_file_upload_log',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(choices=[('PLAN_NORMAL', 'Plan Normal'), ('PLAN_R', 'Plan R')], help_text='Tipo de plan (Plan Normal o Plan R)', max_length=20)),
                ('wh_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Warehouse ID')),
                ('un', models.CharField(blank=True, max_length=50, null=True, verbose_name='UN')),
                ('cliente_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Código Cliente')),
                ('sec_dir', models.CharField(blank=True, max_length=50, null=True, verbose_name='Sec Dir')),
                ('nombre', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre')),
                ('dir_1', models.CharField(blank=True, max_length=300, null=True, verbose_name='Dirección 1')),
                ('dir_2', models.CharField(blank=True, max_length=300, null=True, verbose_name='Dirección 2')),
                ('latitud', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Latitud')),
                ('longitud', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Longitud')),
                ('empresa', models.CharField(blank=True, max_length=200, null=True, verbose_name='Empresa')),
                ('conductor', models.CharField(blank=True, max_length=200, null=True, verbose_name='Conductor')),
                ('placa', models.CharField(blank=True, max_length=20, null=True, verbose_name='Placa')),
                ('carga', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Carga')),
                ('extra_field_1', models.CharField(blank=True, max_length=200, null=True)),
                ('extra_field_2', models.CharField(blank=True, max_length=200, null=True)),
                ('extra_field_3', models.CharField(blank=True, max_length=200, null=True)),
                ('extra_field_4', models.TextField(blank=True, null=True)),
                ('extra_field_5', models.TextField(blank=True, null=True)),
                ('file_source', models.CharField(help_text='Nombre del archivo original', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plan de Entrega',
                'verbose_name_plural': 'Planes de Entrega',
                'db_table': 'operations_delivery_plan',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['plan_type', 'created_at'], name='operations__plan_ty_268b2c_idx'), models.Index(fields=['cliente_code'], name='operations__cliente_4b2664_idx'), models.Index(fields=['placa'], name='operations__placa_a8cf7b_idx')],
            },
        ),
    ]
