# Generated by Django 5.0.7 on 2025-11-14 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion_modulo', models.CharField(max_length=100, unique=True, verbose_name='Descripción')),
                ('order', models.IntegerField(default=0, verbose_name='Orden')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Usuario de creación')),
            ],
            options={
                'verbose_name': 'Módulo',
                'verbose_name_plural': 'Módulos',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Pagina',
            fields=[
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion_pages', models.CharField(max_length=100, verbose_name='Descripción')),
                ('order', models.IntegerField(default=0, verbose_name='Orden')),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paginas', to='maestras.modulo', verbose_name='Módulo')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Usuario de creación')),
            ],
            options={
                'verbose_name': 'Página',
                'verbose_name_plural': 'Páginas',
                'ordering': ['order'],
                'unique_together': {('modulo', 'descripcion_pages')},
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion_rol', models.CharField(max_length=100, unique=True, verbose_name='Descripción')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Usuario de creación')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'ordering': ['descripcion_rol'],
            },
        ),
        migrations.CreateModel(
            name='Tab',
            fields=[
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('id_tab', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion_tabs', models.CharField(max_length=100, verbose_name='Descripción')),
                ('pagina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tabs', to='maestras.pagina', verbose_name='Página')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Usuario de creación')),
            ],
            options={
                'verbose_name': 'Tab',
                'verbose_name_plural': 'Tabs',
                'ordering': ['pagina__order', 'descripcion_tabs'],
                'unique_together': {('pagina', 'descripcion_tabs')},
            },
        ),
        migrations.CreateModel(
            name='PermisoPorUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('ver', models.BooleanField(default=False)),
                ('crear', models.BooleanField(default=False)),
                ('editar', models.BooleanField(default=False)),
                ('borrar', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos_especiales', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Usuario de creación')),
                ('tab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos_usuario', to='maestras.tab', verbose_name='Tab')),
            ],
            options={
                'verbose_name': 'Permiso por Usuario',
                'verbose_name_plural': 'Permisos por Usuario',
                'unique_together': {('usuario', 'tab')},
            },
        ),
        migrations.CreateModel(
            name='PermisoPorRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('ver', models.BooleanField(default=False)),
                ('crear', models.BooleanField(default=False)),
                ('editar', models.BooleanField(default=False)),
                ('borrar', models.BooleanField(default=False)),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Usuario de creación')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos', to='maestras.rol', verbose_name='Rol')),
                ('tab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos_rol', to='maestras.tab', verbose_name='Tab')),
            ],
            options={
                'verbose_name': 'Permiso por Rol',
                'verbose_name_plural': 'Permisos por Rol',
                'unique_together': {('rol', 'tab')},
            },
        ),
    ]
