# Generated by Django 5.0.7 on 2025-12-11 18:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('maestras', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='permisoporusuario',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='modulo',
            name='es_expansivo',
            field=models.BooleanField(default=True, verbose_name='Es Expansivo'),
        ),
        migrations.AddField(
            model_name='pagina',
            name='icono',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Icono'),
        ),
        migrations.AddField(
            model_name='pagina',
            name='route',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ruta'),
        ),
        migrations.AddField(
            model_name='permisoporusuario',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permisos_usuario', to='core.cliente', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='tab',
            name='icono',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Icono'),
        ),
        migrations.AddField(
            model_name='tab',
            name='route',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ruta'),
        ),
        migrations.AlterUniqueTogether(
            name='permisoporusuario',
            unique_together={('usuario', 'tab', 'cliente')},
        ),
    ]
