# Generated by Django 5.0.7 on 2025-12-11 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestras', '0002_alter_permisoporusuario_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulo',
            name='route',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ruta'),
        ),
    ]
