# Generated by Django 5.0.7 on 2026-01-05 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0009_alter_encsolicitud_estado'),
        ('maestras', '0007_remove_estado_usuario_creacion_masterestado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Estado',
        ),
    ]
