# Generated by Django 5.0.7 on 2026-01-14 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestras', '0008_delete_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rol',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maestras.masterestado', verbose_name='Estado'),
        ),
    ]
