# Generated by Django 5.0.7 on 2025-12-30 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EncSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('un_orig', models.CharField(blank=True, max_length=255, null=True)),
                ('f_demanda', models.DateField(blank=True, null=True)),
                ('n_ped', models.CharField(blank=True, max_length=255, null=True)),
                ('placa', models.CharField(blank=True, max_length=50, null=True)),
                ('remision_transferencia', models.CharField(blank=True, max_length=255, null=True)),
                ('carga', models.CharField(blank=True, max_length=255, null=True)),
                ('direccion_1', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('fecha_control', models.DateTimeField(auto_now_add=True)),
                ('usuario_control', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'enc_solicitud',
            },
        ),
        migrations.CreateModel(
            name='DetalleSolicitud',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('articulo', models.CharField(blank=True, max_length=255, null=True)),
                ('cant_env', models.IntegerField(blank=True, null=True)),
                ('total_volume', models.FloatField(blank=True, null=True)),
                ('um', models.CharField(blank=True, max_length=50, null=True)),
                ('volumen', models.FloatField(blank=True, null=True)),
                ('encabezado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='logistics.encsolicitud')),
            ],
            options={
                'db_table': 'detalle_solicitud',
            },
        ),
    ]
