# Generated by Django 5.0.7 on 2026-01-02 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
        ('maestras', '0005_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='encsolicitud',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes', to='maestras.estado', verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='encsolicitud',
            name='fecha_carge',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='encsolicitud',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='encsolicitud',
            name='usuario_carge',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
