# Generated by Django 5.0.7 on 2026-01-02 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_encsolicitud_estado_encsolicitud_fecha_carge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='encsolicitud',
            name='plan_type',
            field=models.CharField(choices=[('PLAN_NORMAL', 'Plan Normal'), ('PLAN_R', 'Plan R')], default='PLAN_NORMAL', max_length=20),
        ),
    ]
