# Generated by Django 5.0.7 on 2026-01-03 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_articulo_factor_especial_articulo_factor_general_and_more'),
        ('logistics', '0003_encsolicitud_plan_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recepcion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('EN_PROCESO', 'En Proceso'), ('REVISION', 'En Revisión'), ('FINALIZADO_OK', 'Finalizado OK'), ('FINALIZADO_CON_NOVEDAD', 'Finalizado con Novedad')], default='EN_PROCESO', max_length=50)),
                ('usuario', models.CharField(blank=True, max_length=255, null=True)),
                ('intentos_fallidos', models.IntegerField(default=0)),
                ('encabezado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recepciones', to='logistics.encsolicitud')),
            ],
            options={
                'db_table': 'recepcion',
            },
        ),
        migrations.CreateModel(
            name='DetalleRecepcion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_contada_base', models.FloatField(default=0.0)),
                ('novedad', models.BooleanField(default=False)),
                ('articulo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.articulo')),
                ('recepcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='logistics.recepcion')),
            ],
            options={
                'db_table': 'detalle_recepcion',
            },
        ),
    ]
