# Generated by Django 5.0.7 on 2026-01-04 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0004_recepcion_detallerecepcion'),
        ('maestras', '0006_tiponotificacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorreosNotificacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('correo', models.EmailField(max_length=255)),
                ('nombre_contacto', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre Contacto/Usuario')),
                ('estado', models.BooleanField(default=True)),
                ('usuario_registro', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('tipo_novedad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correos_suscritos', to='maestras.tiponotificacion')),
            ],
            options={
                'verbose_name': 'Correo de Notificación',
                'verbose_name_plural': 'Correos de Notificación',
                'db_table': 'correos_notificacion',
            },
        ),
    ]
