# Generated by Django 5.0.7 on 2026-01-04 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0005_correosnotificacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encsolicitud',
            name='remision_transferencia',
        ),
        migrations.AddField(
            model_name='detallesolicitud',
            name='remision_transferencia',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
