# Generated by Django 5.0.7 on 2026-01-04 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0006_remove_encsolicitud_remision_transferencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallesolicitud',
            name='n_ped',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
