# Generated by Django 5.0.7 on 2026-01-05 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_articulo_factor_especial_articulo_factor_general_and_more'),
        ('logistics', '0007_detallesolicitud_n_ped'),
    ]

    operations = [
        migrations.CreateModel(
            name='Despacho',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_despacho', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('PLANIFICADO', 'Planificado'), ('EN_RUTA', 'En Ruta'), ('ENTREGADO', 'Entregado')], default='PLANIFICADO', max_length=50)),
                ('capacidad_ocupada', models.FloatField(default=0.0)),
                ('usuario_creacion', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('conductor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.conductor')),
                ('vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.vehiculo')),
            ],
            options={
                'db_table': 'despacho',
            },
        ),
        migrations.CreateModel(
            name='DetalleDespacho',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pedido_n', models.CharField(blank=True, max_length=255, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('volumen_total', models.FloatField(default=0.0)),
                ('peso_total', models.FloatField(default=0.0)),
                ('despacho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='logistics.despacho')),
            ],
            options={
                'db_table': 'detalle_despacho',
            },
        ),
    ]
