# Generated by Django 5.0.7 on 2026-01-05 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0008_despacho_detalledespacho'),
        ('maestras', '0007_remove_estado_usuario_creacion_masterestado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encsolicitud',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes', to='maestras.masterestado', verbose_name='Estado'),
        ),
    ]
