# Generated by Django 5.0.7 on 2026-01-05 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0009_alter_encsolicitud_estado'),
        ('maestras', '0008_delete_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='correosnotificacion',
            name='estado_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correos', to='maestras.masterestado'),
        ),
        migrations.AddField(
            model_name='despacho',
            name='estado_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despachos', to='maestras.masterestado'),
        ),
        migrations.AddField(
            model_name='recepcion',
            name='estado_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recepciones', to='maestras.masterestado'),
        ),
    ]
