# Generated by Django 5.0.7 on 2026-01-05 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0011_remove_correosnotificacion_estado_fk_and_more'),
        ('maestras', '0008_delete_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='despacho',
            name='estado',
        ),
        migrations.RenameField(
            model_name='despacho',
            old_name='estado_fk',
            new_name='estado',
        ),
    ]
