# Generated by Django 5.0.7 on 2025-12-15 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_conductor_licencia'),
        ('users', '0002_alter_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='clientes',
            field=models.ManyToManyField(blank=True, related_name='usuarios_asignados', to='core.cliente'),
        ),
    ]
