# Generated by Django 5.0.7 on 2025-12-16 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_clientes'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='eliminado',
            field=models.BooleanField(default=False, verbose_name='Eliminado'),
        ),
    ]
