# Generated by Django 5.0.7 on 2025-12-11 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('cadena', 'Cadena'), ('independiente', 'Independiente')], max_length=15)),
                ('direccion', models.TextField()),
                ('zona', models.CharField(max_length=50)),
                ('representante', models.CharField(blank=True, max_length=150, verbose_name='Representante')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('logo', models.CharField(blank=True, max_length=255, verbose_name='Ruta del Logo')),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=15, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('celular', models.CharField(max_length=15)),
                ('licencia', models.CharField(max_length=20)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('propietario', models.CharField(max_length=100)),
                ('cubicaje', models.DecimalField(decimal_places=2, max_digits=6)),
                ('modelo', models.CharField(max_length=50)),
                ('disponible', models.BooleanField(default=True)),
            ],
        ),
    ]
