# Generated by Django 5.0.7 on 2025-12-12 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_change_logo_to_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='clientes/logos/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='cubicaje',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
