# Generated by Django 5.0.7 on 2025-12-12 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_cliente_logo_alter_vehiculo_cubicaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='eliminado',
            field=models.BooleanField(default=False, verbose_name='Eliminado'),
        ),
        migrations.AddField(
            model_name='conductor',
            name='eliminado',
            field=models.BooleanField(default=False, verbose_name='Eliminado'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='eliminado',
            field=models.BooleanField(default=False, verbose_name='Eliminado'),
        ),
    ]
