# Generated by Django 5.0.7 on 2025-12-12 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_cliente_eliminado_conductor_eliminado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conductor',
            name='licencia',
            field=models.JSONField(default=list, verbose_name='Categorías de Licencia'),
        ),
    ]
