# Generated by Django 5.0.7 on 2025-12-16 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_tipovehiculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='tipo_vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tipovehiculo', verbose_name='Tipo de Vehículo'),
        ),
    ]
