# Generated by Django 5.0.7 on 2025-12-16 03:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_vehiculo_tipo_vehiculo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100, unique=True)),
                ('estado', models.BooleanField(default=True)),
                ('eliminado', models.BooleanField(default=False, verbose_name='Eliminado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categorias_created', to=settings.AUTH_USER_MODEL, verbose_name='Usuario de creación')),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categorias_modified', to=settings.AUTH_USER_MODEL, verbose_name='Usuario de modificación')),
            ],
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('unidad_medida_general', models.CharField(max_length=20, verbose_name='Unidad Medida General')),
                ('unidad_medida_especial', models.CharField(blank=True, max_length=20, null=True, verbose_name='Unidad Medida Especial')),
                ('unidad_medida_intermedia', models.CharField(blank=True, max_length=20, null=True, verbose_name='Unidad Medida Intermedia')),
                ('estado', models.BooleanField(default=True)),
                ('eliminado', models.BooleanField(default=False, verbose_name='Eliminado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articulos_created', to=settings.AUTH_USER_MODEL, verbose_name='Usuario de creación')),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articulos_modified', to=settings.AUTH_USER_MODEL, verbose_name='Usuario de modificación')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.categoria', verbose_name='Categoría')),
            ],
        ),
    ]
