# Generated by Django 5.0.7 on 2025-12-16 03:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_categoria_articulo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100, unique=True, verbose_name='Descripción')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('eliminado', models.BooleanField(default=False, verbose_name='Eliminado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unidades_medida_created', to=settings.AUTH_USER_MODEL, verbose_name='Usuario de creación')),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unidades_medida_modified', to=settings.AUTH_USER_MODEL, verbose_name='Usuario de modificación')),
            ],
        ),
        migrations.AlterField(
            model_name='articulo',
            name='unidad_medida_especial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articulos_especial', to='core.unidadmedida', verbose_name='Unidad Medida Especial'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='unidad_medida_general',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articulos_general', to='core.unidadmedida', verbose_name='Unidad Medida General'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='unidad_medida_intermedia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articulos_intermedia', to='core.unidadmedida', verbose_name='Unidad Medida Intermedia'),
        ),
    ]
