# Generated by Django 5.0.7 on 2025-12-16 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_unidadmedida_alter_articulo_unidad_medida_especial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidadmedida',
            name='abreviatura',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Abreviatura'),
        ),
    ]
