# Generated by Django 5.0.7 on 2025-12-16 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_unidadmedida_abreviatura'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='codigo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Código'),
        ),
    ]
