# Generated by Django 5.0.7 on 2026-01-03 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_articulo_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='factor_especial',
            field=models.FloatField(default=1.0, verbose_name='Factor Especial'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='factor_general',
            field=models.FloatField(default=1.0, verbose_name='Factor General (Base)'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='factor_intermedio',
            field=models.FloatField(default=1.0, verbose_name='Factor Intermedio'),
        ),
    ]
