# Generated by Django 5.0.7 on 2026-01-14 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_articulo_factor_especial_articulo_factor_general_and_more'),
        ('maestras', '0008_delete_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculo',
            name='disponible',
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maestras.masterestado', verbose_name='Estado'),
        ),
    ]
