# Generated by Django 5.0.7 on 2026-01-14 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_vehiculo_disponible_vehiculo_estado'),
        ('maestras', '0008_delete_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conductor',
            name='activo',
        ),
        migrations.AddField(
            model_name='conductor',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maestras.masterestado', verbose_name='Estado'),
        ),
    ]
