# Generated by Django 5.0.7 on 2026-01-14 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_cliente_estado'),
        ('maestras', '0008_delete_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maestras.masterestado', verbose_name='Estado'),
        ),
    ]
